[build]
    functions = "functions"
[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200
[[headers]]
    # Define which paths this specific [[headers]] block will cover.
    for = "/.netlify/functions/*"
        [headers.values]
        Access-Control-Allow-Origin = "*"